#端口
server:
  port: 8080
spring:
#数据源
  datasource:
    url: jdbc:mysql://118.25.217.38:3306/myitems?useUnicode=true&characterEncoding=utf-8&useSSL=false
    name: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    max-active: 20
    max-idle: 8
    min-idle: 8
    initial-size: 10
#thymeleaf配置
  thymeleaf:
    prefix: classpath:/templates/pages/
    enabled: false
    suffix: .html
    mode: HTML5
    encoding: utf-8
    servlet:
      content-type: text/html
#mapper.xml所在位置
mybatis:
  mapper-locations: classpath:mapper/*.xml
